inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - config/*
    - config/**/*
    - vendor/**/*
    - tmp/**/*
    - bin/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*